server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: java
    password: java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
